Fail is pa11y is unable to scan the site

diff --git a/.github/workflows/pa11y.yml b/.github/workflows/pa11y.yml
--- a/.github/workflows/pa11y.yml
+++ b/.github/workflows/pa11y.yml
@@ -43,6 +43,12 @@ jobs:
         with:
           path: ./pa11y_output.txt
 
+      - name: verify that pa11y successfully scanned the site
+        if: contains(steps.pa11y_output.outputs.content, 'ailed to run')
+        run: |
+          echo "::error::Pa11y failed to run."
+          exit 1
+
       - name: Comment on pull request.
         uses: thollander/actions-comment-pull-request@v2
         with:
